<?php

/**
 * @file
 * Display Suite Bootstrap 5 7 configuration.
 */

function ds_bootstrap_5_7() {
  return array(
    'label' => t('Bootstrap 5 7'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_5_7.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_5_7.png)
    // 'image' => TRUE,
  );
}
