<?php

/**
 * @file
 * Display Suite Bootstrap 8 4 configuration.
 */

function ds_bootstrap_8_4() {
  return array(
    'label' => t('Bootstrap 8 4'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_8_4.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_8_4.png)
    // 'image' => TRUE,
  );
}
