<?php

/**
 * @file
 * Display Suite Bootstrap 4 8 configuration.
 */

function ds_bootstrap_4_8() {
  return array(
    'label' => t('Bootstrap 4 8'),
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_4_8.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_4_8.png)
    // 'image' => TRUE,
  );
}
