<?php

/**
 * @file
 * Display Suite Bootstrap 12 3 9 configuration.
 */

function ds_bootstrap_12_3_9() {
  return array(
    'label' => t('Bootstrap 12 3 9'),
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (bootstrap_12_3_9.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (bootstrap_12_3_9.png)
    // 'image' => TRUE,
  );
}
